---
title: "In-class Exercise 2"
author: "kai feng"
date: "August 26, 2024"
date-modified: "last-modified"
execute:
  eval: true
  echo: true
  freeze: true
---

```{r}
pacman::p_load(tidyverse, sf, ggstatsplot, tmap)
```

```{r}
mpsz2014_shp = st_read(dsn = "data/MasterPlan2014SubzoneBoundaryWebSHP",                 
               layer = "MP14_SUBZONE_WEB_PL")
```

To know the data type:

```{r}
class(mpsz2014_shp)
```

```{r}
#| eval: false
mpsz2014_kml = st_read("data/MasterPlan2014SubzoneBoundaryWebKML.kml")
```

```{r}
#| output: false
st_write(mpsz2014_shp,
         "data/MP14_SUBZONE_WEB_PL.kml",
         delete_dsn = TRUE)
```

```{r}
mpsz2014_kml = st_read("data/MP14_SUBZONE_WEB_PL.kml")
```

```{r}
mpsz2019_shp = st_read(dsn = "data/MPSZ-2019",                 
               layer = "MPSZ-2019") %>%
  st_transform(crs = 3414)
        
```

```{r}
mpsz2019_kml = st_read("data/MasterPlan2019SubzoneBoundaryNoSeaKML.kml")
```

```{r}
popdata <- read.csv("data/respopagesextod2023/respopagesextod2023.csv")
```

```{r}
popdata2023 <- popdata %>%
  group_by(PA, SZ, AG) %>%
  summarise(`POP`=sum(`Pop`)) %>%
  ungroup() %>%
  pivot_wider(names_from=AG,
              values_from = POP)

colnames(popdata2023)
```

```{r}
popdata2023 <- popdata %>%
  filter(Time == 2023) %>%
  group_by(PA, SZ, AG) %>%
  summarise(`POP` = sum(`Pop`)) %>%
  ungroup()%>%
  pivot_wider(names_from=AG, 
              values_from=POP) %>%
  mutate(YOUNG = rowSums(.[3:6])
         +rowSums(.[12])) %>%
mutate(`ECONOMY ACTIVE` = rowSums(.[7:11])+
rowSums(.[13:15]))%>%
mutate(`AGED`=rowSums(.[16:21])) %>%
mutate(`TOTAL`=rowSums(.[3:21])) %>%  
mutate(`DEPENDENCY` = (`YOUNG` + `AGED`)
/`ECONOMY ACTIVE`)
```


```{r}
popdata2023 <- popdata2023 %>%
  mutate_at(.vars = vars(PA, SZ), 
          .funs = list(toupper)) %>%
  filter(`ECONOMY ACTIVE` > 0)
```

```{r}
mpsz_pop2023 <- left_join(mpsz, popdata2023,
                          by = c("SUBZONE_N" = "SZ"))
```